// <auto-generated />
using System;
using IssueViewer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssueViewer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181130064052_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("IssueViewer.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("ClosedDateTime");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<int>("IssueId");

                    b.Property<DateTime>("LastUpdatedDateTime");

                    b.Property<string>("Link");

                    b.Property<string>("RepoId");

                    b.Property<int>("State");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
